const Image = {
  lambSamosa: require("./lambSamosa.jpg"),
  eggPakoda: require("./eggPakoda.jpg"),
  chickenPakoda: require("./chickenPakoda.jpg"),
  vegetablePakoda: require("./vegetablePakora.avif"),
  channaChatt: require("./chanaChatt.jpg"),
  samosaChatt: require("./samosaChaat.jpg"),
  chickenTandoori: require("./chickenTandoori.jpg"),
  quailTandoori: require("./tandooriQuail.jpg"),
  lambTandoori: require("./tandooriLamb.jpg"),
  shrimpTandoori: require("./shrimpTandoori.webp"),
  poori: require("./poori.jpg"),
  naan: require("./naan.webp"),
  garlicNaan: require("./garlicNaan.webp"),
  roti: require("./roti.webp"),
  alooParatha: require("./alooParatha.jpg"),
  vegBriyani: require("./vegBriyani.jpg"),
  chickenBiyani: require("./chickenBriyani.jpg"),
  lambBriyani: require("./lambBriyani.jpg"),
  scallopBriyani: require("./scallopBriyani.jpg"),
};
export default Image;
